name: release-wf-1
on: push
jobs:
    job-1:
        name: release-wf
        runs-on: ubuntu-latest
        steps:
            - name: get sources
              uses: actions/checkout@v4
            - name: install npm
              run: npm i
            - name: build
              run: npm run build